site_name: FFA Framework
nav:
  - Home: index.md
  - Command Line Interface:
    - Getting Started: cli-introduction.md
    - Installation Instructions: cli-installation.md
    - User Manual: cli-manual.md
  - R Package:
    - Installation instructions: r-installation.md
    - User Manual: r-documentation.pdf
    - Vignettes:
      - "Introduction": vignettes/introduction.html
      - "Change Point Detection": vignettes/change-points.html
      - "Trend Identification": vignettes/trend-identification.html
      - "Stationary FFA": vignettes/stationary-ffa.html
      - "Non-Stationary FFA": vignettes/non-stationary-ffa.html
  - Concepts:
    - Exploratory Data Analysis: eda.md
    - Probability Distributions: distributions.md
    - Model Selection: model-selection.md
    - Parameter Estimation: parameter-estimation.md
    - Frequency Analysis: frequency-analysis.md
    - Uncertainty Quantification: uncertainty-quantification.md
    - Model Assessment: model-assessment.md
  - About:
    - Goals: goals.md
    - Roadmap: roadmap.md
    - Release Notes: changelog.md
    - MATLAB Version: matlab.md
    - License: license.md
theme: readthedocs
markdown_extensions:
  pymdownx.arithmatex:
    generic: True
  footnotes:
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-chtml-full.min.js
