site_name: FFA Framework
nav:
  - Home: index.md
  - R Package:
    - Documentation: r-documentation.pdf
  - Command Line Interface:
    - Installation Instructions: cli-installation.md
    - User Manual: cli-manual.md
  - Concepts:
    - Exploratory Data Analysis: eda.md
    - Probability Distributions: distributions.md
    - Model Selection: model-selection.md
    - Parameter Estimation: parameter-estimation.md
    - Frequency Analysis: frequency-analysis.md
    - Uncertainty Quantification: uncertainty-quantification.md
    - Model Assessment: model-assessment.md
  - About:
    - Goals: goals.md
    - Roadmap: roadmap.md
    - Release Notes: changelog.md
    - MATLAB Version: matlab.md
    - License: license.md
theme: readthedocs
markdown_extensions:
  pymdownx.arithmatex:
    generic: True
  footnotes:
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-chtml-full.min.js
